import {getEnv} from '../../../configs';

export const AuthConfigs = {
  ACCESS_TOKEN_SECRET: getEnv('ACCESS_TOKEN_SECRET', 'hjhgbh'),
  REFRESH_TOKEN_SECRET: getEnv('REFRESH_TOKEN_SECRET', 'vhgvhgv'),
  TOKEN_SECRET_LIFE: getEnv('TOKEN_SECRET_LIFE', '20m'),
  REFRESH_TOKEN_SECRET_LIFE: getEnv('REFRESH_TOKEN_SECRET_LIFE', '30m'),
  TOKEN_KEY: getEnv('TOKEN_AUTH_USER', 'gfghgyj'),
  TOKEN_EXPIRATION_TIME: getEnv('TOKEN_EXPIRATION_TIME', '5m'),
  REFRESH_TOKEN_EXPIRATION_TIME: getEnv('REFRESH_TOKEN_EXPIRATION_TIME', '40m'),
  TOKEN_HEADER_KEY: getEnv('TOKEN_HEADER_KEY'),
  PASSWORD_RESET_TOKEN_KEY: getEnv('PASSWORD_RESET_TOKEN_KEY', 'kaHelhjbvghb'),
  PASSWORD_RESET_TOKEN_EXPIRATION_TIME:
   getEnv('PASSWORD_RESET_TOKEN_EXPIRATION_TIME', '20m'),
  COOKIES_KEY: getEnv('COOKIES_KEY', 'jks32jic3dfj434hb'),
  TOKEN_DATA_KEY_NAME: getEnv('COOKIES_KEY', 'tokenData'),
  VERIFICATION_EXPIRATION_TIME: getEnv('VERIFICATION_EXPIRATION_TIME'),
};
